USE codeup_test_db;

INSERT INTO albums (artist, name, release_date, genre, sales)
VALUES ('Michael Jackson', 'Thriller',	1982,	'Pop, rock, R&B', 66),
('Eagles', 'Their Greatest Hits (1971–1975)', 1976,
    'Country rock, soft rock, folk rock', 51),
('AC/DC',	'Back in Black', 1980, 'Hard rock', 50),
('Pink Floyd',	'The Dark Side of the Moon', 1973, 'Progressive rock', 45),
('Whitney Houston',	'The Bodyguard',	1992,	'R&B, soul, pop, soundtrack', 45),
('Meat Loaf',	'Bat Out of Hell', 1977,	'Hard rock, glam rock, heavy metal', 43),
('Eagles', 'Hotel California',	1976,	'Soft rock', 42),
('Bee Gees / Various artists', 'Saturday Night Fever',	1977,	'Disco', 40),
('Fleetwood Mac',	'Rumours', 1977,	'Soft rock', 40),
('Shania Twain', 'Come On Over',	1997,	'Country, pop', 40),
('Various artists',
    'Grease: The Original Soundtrack from the Motion Picture', 1978,
    'Rock and roll', 38),
('Led Zeppelin', 'Led Zeppelin IV', 1971,
  'Hard rock, heavy metal, folk rock', 37),
('Michael Jackson',	'Bad', 1987, 'Pop, funk, rock', 35),
('Alanis Morissette',	'Jagged Little Pill',	1995,	'Alternative rock', 33),
('Celine Dion',	'Falling into You',	1996,	'Pop, soft rock', 32),
('The Beatles',	'Sgt. Pepper''s Lonely Hearts Club Band',	1967,	'Rock', 32),
('Various Artists',	'Dirty Dancing', 1987, 'Pop, rock, R&B', 32),
('Michael Jackson',	'Dangerous', 1991,	'Rock, funk, pop', 32),
('Adele',	'21',	2011,	'Pop, soul', 31),
('Celine Dion',	'Let''s Talk About Love',	1997,	'Pop, soft rock', 31),
('The Beatles',	'1', 2000, 'Rock', 31),
('Metallica',	'Metallica', 1991,'Heavy metal', 31),
('Nirvana',	'Nevermind',	1991,	'Grunge, alternative rock',	30),
('Pink Floyd',	'The Wall',	1979,	'Progressive rock',	30),
('Santana',	'Supernatural',	1999,	'Latin rock',	30),
('Guns N'' Roses',	'Appetite for Destruction',	1987,	'Hard rock',	30)